targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/models/**
      json_serializable:
        generate_for:
          include:
            - lib/models/**
