// File generated by FlutterFire CLI or defined manually for project setup.
// To fully configure Firebase, run: flutterfire configure
// Or paste your web, android, and ios configurations below.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux options not configured.');
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQRNFs0X5qeeuboGI6dhU6POtWXhUKdw4',
    appId: '1:667764839320:web:67c92248f946ea81b7d1ed',
    messagingSenderId: '667764839320',
    projectId: 'dershub-d6b93',
    authDomain: 'dershub-d6b93.firebaseapp.com',
    storageBucket: 'dershub-d6b93.firebasestorage.app',
    measurementId: 'G-7159C0WTH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBFQ4KPQytmjIBynHmrSWo454moxsBq1A',
    appId: '1:667764839320:android:6ba0324deadc21a1b7d1ed',
    messagingSenderId: '667764839320',
    projectId: 'dershub-d6b93',
    storageBucket: 'dershub-d6b93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHQpku_9osDOx1RH-V6zYTCodVrs1ZZ5A',
    appId: '1:667764839320:ios:9b80139c648c2a07b7d1ed',
    messagingSenderId: '667764839320',
    projectId: 'dershub-d6b93',
    storageBucket: 'dershub-d6b93.firebasestorage.app',
    iosBundleId: 'com.example.dershub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHQpku_9osDOx1RH-V6zYTCodVrs1ZZ5A',
    appId: '1:667764839320:ios:9b80139c648c2a07b7d1ed',
    messagingSenderId: '667764839320',
    projectId: 'dershub-d6b93',
    storageBucket: 'dershub-d6b93.firebasestorage.app',
    iosBundleId: 'com.example.dershub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQRNFs0X5qeeuboGI6dhU6POtWXhUKdw4',
    appId: '1:667764839320:web:48ac8a74ae0017b8b7d1ed',
    messagingSenderId: '667764839320',
    projectId: 'dershub-d6b93',
    authDomain: 'dershub-d6b93.firebaseapp.com',
    storageBucket: 'dershub-d6b93.firebasestorage.app',
    measurementId: 'G-HRFNRVSH2P',
  );

}